// <auto-generated />
using System;
using ArcDrop.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArcDrop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ArcDropDbContext))]
    [Migration("20260304032125_AddAiProviderConfig")]
    partial class AddAiProviderConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArcDrop.Domain.Entities.AiProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ApiKeyCipherText")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_provider_configs_provider_name");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_ai_provider_configs_updated_at_utc");

                    b.ToTable("ai_provider_configs", "public");
                });

            modelBuilder.Entity("ArcDrop.Domain.Entities.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_bookmarks_created_at_utc");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_bookmarks_title");

                    b.HasIndex("Url")
                        .HasDatabaseName("ix_bookmarks_url");

                    b.ToTable("bookmarks", "public");
                });

            modelBuilder.Entity("ArcDrop.Domain.Entities.BookmarkCollectionLink", b =>
                {
                    b.Property<Guid>("BookmarkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.HasKey("BookmarkId", "CollectionId");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_bookmark_collection_links_collection_id");

                    b.ToTable("bookmark_collection_links", "public");
                });

            modelBuilder.Entity("ArcDrop.Domain.Entities.BookmarkTag", b =>
                {
                    b.Property<Guid>("BookmarkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("BookmarkId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_bookmark_tags_tag_id");

                    b.ToTable("bookmark_tags", "public");
                });

            modelBuilder.Entity("ArcDrop.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_collections_name");

                    b.ToTable("collections", "public");
                });

            modelBuilder.Entity("ArcDrop.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_tags_name_normalized");

                    b.ToTable("tags", "public");
                });

            modelBuilder.Entity("ArcDrop.Domain.Entities.BookmarkCollectionLink", b =>
                {
                    b.HasOne("ArcDrop.Domain.Entities.Bookmark", "Bookmark")
                        .WithMany("Collections")
                        .HasForeignKey("BookmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcDrop.Domain.Entities.Collection", "Collection")
                        .WithMany("Bookmarks")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookmark");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("ArcDrop.Domain.Entities.BookmarkTag", b =>
                {
                    b.HasOne("ArcDrop.Domain.Entities.Bookmark", "Bookmark")
                        .WithMany("Tags")
                        .HasForeignKey("BookmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcDrop.Domain.Entities.Tag", "Tag")
                        .WithMany("Bookmarks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookmark");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ArcDrop.Domain.Entities.Bookmark", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ArcDrop.Domain.Entities.Collection", b =>
                {
                    b.Navigation("Bookmarks");
                });

            modelBuilder.Entity("ArcDrop.Domain.Entities.Tag", b =>
                {
                    b.Navigation("Bookmarks");
                });
#pragma warning restore 612, 618
        }
    }
}
